NDRCN-232
hmrc/national-duty-repayment-center-frontend pull request #109
Opened 2020-12-01 17:47 UTC by simms11

2020-12-02 09:38 UTC, simms11 commented
Navigation has not been added as this page is  specifically related to the **representative of the importer journey** which has yet to be completed

2020-12-02 09:54 UTC, lmugnai requested changes
Need some specs for this page.

2020-12-03 15:17 UTC, lmugnai requested changes
Hi @simms11 Could you ensure there is a new line character at the end of each file? I've put them in as suggestions so just need to accept the suggestion. Thanks

2020-12-03 15:17 UTC, lmugnai commented on app/controllers/ProofOfAuthorityController.scala
> +}
```suggestion
}

```

2020-12-03 15:17 UTC, lmugnai commented on app/views/ProofOfAuthorityView.scala.html
> +}
```suggestion
}

```

2020-12-03 15:17 UTC, lmugnai commented on conf/app.routes
> +GET         /proofOfAuthority                       controllers.ProofOfAuthorityController.onPageLoad()
```suggestion
GET         /proofOfAuthority                       controllers.ProofOfAuthorityController.onPageLoad()

```

2020-12-03 15:17 UTC, lmugnai commented on conf/messages.en
> +proofOfAuthority.paragraph2 = Upload a file
```suggestion
proofOfAuthority.paragraph2 = Upload a file

```

2020-12-03 15:25 UTC, lmugnai requested changes

2020-12-03 15:25 UTC, lmugnai commented on app/navigation/Navigator.scala
> +    case Some(true)  => routes.ProofOfAuthorityController.onPageLoad()
I think this is wrong. If the user selects 'Yes' they should go to the BankDetails Page. If they select No they should go to the proofofauthority page. That's why I left the case(false) as not implemented (???).

2020-12-03 15:25 UTC, lmugnai commented on test/pages/ProofOfAuthorityPageSpec.scala
> +  "EvidenceSupportingDocsPage" must {
If this does nothing, can we remove it?

2020-12-03 19:22 UTC, lmugnai commented on test/navigation/NavigatorSpec.scala
> +      "go to CheckYourAnswers page after the claimant page once the representative has uploaded their proof of authority" in {
Can we have a chat about this test? It doesn't look right to me but might be missing something?

2020-12-04 11:48 UTC, lmugnai approved these changes

2020-12-04 11:52 UTC, merged