NDRCN-324 Testing Fixes
hmrc/national-duty-repayment-center-frontend pull request #247
Opened 2021-02-12 17:11 UTC by somaraja

2021-02-12 17:20 UTC, anu9 commented on app/views/BulkFileUploadView.scala.html
> -        id = "upload-file",
Does this affect error focus?

2021-02-12 17:23 UTC, somaraja commented on app/views/BulkFileUploadView.scala.html
> -        id = "upload-file",
Yes, fixed this issue

2021-02-12 17:25 UTC, anu9 commented on app/views/BulkFileUploadView.scala.html
> -        id = "upload-file",
lgtm

2021-02-12 17:34 UTC, anu9 commented on app/views/BulkFileUploadView.scala.html
> -        id = "upload-file",
lgtm

2021-02-12 20:04 UTC, chandaksweta requested changes
Overall looks good to me. The refactoring needs to be done and the urls should be in sync

2021-02-12 20:04 UTC, chandaksweta commented on app/controllers/BulkFileUploadController.scala
>    final val COOKIE_JSENABLED = "jsenabled"
this is no longer needed

2021-02-12 20:04 UTC, chandaksweta commented on app/controllers/BulkFileUploadController.scala
>    type ConvertState = (FileUploadState) => Future[FileUploadState]
this is not needed too

2021-02-12 20:04 UTC, chandaksweta commented on app/controllers/BulkFileUploadController.scala
> +  final def successRedirect(id: String)(implicit rh: RequestHeader) = appConfig.baseExternalCallbackUrl + (rh.cookies.get(COOKIE_JSENABLED) match {
This needs refactoring. Get rid of this method and in the callback add the url directly

2021-02-12 20:04 UTC, chandaksweta commented on app/controllers/BulkFileUploadController.scala
>    final def errorRedirect(id: String)(implicit rh: RequestHeader) =
same here

2021-02-12 20:04 UTC, chandaksweta commented on conf/app.routes
>  GET        /upload-multiple-entries                        controllers.BulkFileUploadController.showFileUpload()
the urls for bulk looks mis aligned.

2021-02-12 20:05 UTC, chandaksweta commented on app/controllers/BulkFileUploadController.scala
>                logger.info(s"File uploaded $s")
remove logging.. no longer needed

2021-02-14 19:16 UTC, chandaksweta approved these changes

2021-02-15 09:29 UTC, merged